import type { ModuleMeta } from "@/lib/types";

export const moduleMetas: ModuleMeta[] = [
  {
    slug: "01-bem-vindo-atlasgr",
    number: 1,
    title: "Bem-vindo à ATLASGR",
    shortDescription: "História, propósito, valores, cultura e organograma da empresa.",
    durationMinutes: 40,
    status: "ready", category: "Fundamentos",
  },
  {
    slug: "02-mercado-logistica",
    number: 2,
    title: "Mercado de Logística",
    shortDescription: "Supply chain, transportadoras, embarcadores e tipos de carga e operação.",
    durationMinutes: 35,
    status: "ready", category: "Fundamentos",
  },
  {
    slug: "03-gerenciamento-risco",
    number: 3,
    title: "Gerenciamento de Risco",
    shortDescription: "Do conceito básico ao avançado: PGR, apólice, sinistro e o papel da Central.",
    durationMinutes: 55,
    status: "ready", category: "Fundamentos",
  },
  {
    slug: "04-produtos-atlasgr",
    number: 4,
    title: "Produtos ATLASGR",
    shortDescription: "Visão geral do portfólio: gerenciamento de risco, tecnologia, perfil securitário e bases dedicadas.",
    durationMinutes: 45,
    status: "ready", category: "Soluções ATLASGR",
  },
  {
    slug: "05-software-logistico",
    number: 5,
    title: "Software Logístico — Sistema Atlas Connect",
    shortDescription: "Telas, funcionalidades e fluxo de trabalho do sistema Atlas Connect.",
    durationMinutes: 50,
    status: "ready", category: "Soluções ATLASGR",
  },
  {
    slug: "06-atlas-profile",
    number: 6,
    title: "Atlas Profile",
    shortDescription: "Background check, biometria e compliance na análise de motoristas e veículos.",
    durationMinutes: 35,
    status: "ready", category: "Soluções ATLASGR",
  },
  {
    slug: "07-integracoes",
    number: 7,
    title: "Integrações",
    shortDescription: "Como o Atlas Connect conversa com ERP, TMS e rastreadores de diferentes fabricantes.",
    durationMinutes: 30,
    status: "ready", category: "Soluções ATLASGR",
  },
  {
    slug: "08-clientes",
    number: 8,
    title: "Clientes",
    shortDescription: "Perfis de cliente atendidos pela Atlas: transportadoras, embarcadores e segmentos.",
    durationMinutes: 30,
    status: "ready", category: "Mercado e clientes",
  },
  {
    slug: "09-processo-comercial",
    number: 9,
    title: "Processo Comercial",
    shortDescription: "ICP, persona, dores, objeções, diferenciais competitivos e argumentação.",
    durationMinutes: 40,
    status: "ready", category: "Mercado e clientes",
  },
  {
    slug: "10-termos-tecnicos",
    number: 10,
    title: "Termos Técnicos",
    shortDescription: "Glossário consolidado com os termos usados no dia a dia da Central e do mercado.",
    durationMinutes: 30,
    status: "ready", category: "Excelência operacional",
  },
  {
    slug: "11-operacao",
    number: 11,
    title: "Operação",
    shortDescription: "Fluxos, monitoramento, checklist, alertas e eventos do dia a dia da Central.",
    durationMinutes: 45,
    status: "ready", category: "Excelência operacional",
  },
  {
    slug: "12-compliance",
    number: 12,
    title: "Compliance",
    shortDescription: "LGPD, segurança da informação, sigilo e boas práticas internas.",
    durationMinutes: 30,
    status: "ready", category: "Excelência operacional",
  },
  {
    slug: "13-tecnologia",
    number: 13,
    title: "Tecnologia",
    shortDescription: "IA, analytics e automações aplicadas ao gerenciamento de risco logístico.",
    durationMinutes: 35,
    status: "ready", category: "Excelência operacional",
  },
  {
    slug: "14-casos-reais",
    number: 14,
    title: "Casos Reais",
    shortDescription: "Cases, recuperações e resultados operacionais da Atlas.",
    durationMinutes: 30,
    status: "ready", category: "Excelência operacional",
  },
  {
    slug: "15-preparacao-final",
    number: 15,
    title: "Preparação Final",
    shortDescription: "Revisão geral de todo o conteúdo antes da prova final.",
    durationMinutes: 30,
    status: "ready", category: "Conclusão",
  },
];

export function getModuleMeta(slug: string): ModuleMeta | undefined {
  return moduleMetas.find((m) => m.slug === slug);
}
