import type { ModuleMeta } from "@/lib/types";

export const moduleMetas: ModuleMeta[] = [
  {
    slug: "01-bem-vindo-totaltrac",
    number: 1,
    title: "Bem-vindo à Total Trac",
    shortDescription: "História, propósito, valores, cultura e organograma da empresa.",
    durationMinutes: 40,
    academy: "totaltrac", status: "ready", category: "Fundamentos",
  },
  {
    slug: "02-mercado-logistica",
    number: 2,
    title: "Mercado de Logística",
    shortDescription: "Supply chain, transportadoras, embarcadores e tipos de carga e operação.",
    durationMinutes: 35,
    academy: "totaltrac", status: "ready", category: "Fundamentos",
  },
  {
    slug: "03-gerenciamento-risco",
    number: 3,
    title: "Gerenciamento de Risco",
    shortDescription: "Do conceito básico ao avançado: PGR, apólice, sinistro e o papel da Central.",
    durationMinutes: 55,
    academy: "totaltrac", status: "ready", category: "Fundamentos",
  },
  {
    slug: "04-produtos-totaltrac",
    number: 4,
    title: "Produtos Total Trac",
    shortDescription: "Visão geral do portfólio: gerenciamento de risco, tecnologia, perfil securitário e bases dedicadas.",
    durationMinutes: 45,
    academy: "totaltrac", status: "ready", category: "Soluções Total Trac",
  },
  {
    slug: "05-software-logistico",
    number: 5,
    title: "Software Logístico — Sistema Total Trac Connect",
    shortDescription: "Telas, funcionalidades e fluxo de trabalho do sistema Total Trac Connect.",
    durationMinutes: 50,
    academy: "totaltrac", status: "ready", category: "Soluções Total Trac",
  },
  {
    slug: "06-atlas-profile",
    number: 6,
    title: "Atlas Profile",
    shortDescription: "Background check, biometria e compliance na análise de motoristas e veículos.",
    durationMinutes: 35,
    academy: "totaltrac", status: "ready", category: "Soluções Total Trac",
  },
  {
    slug: "07-integracoes",
    number: 7,
    title: "Integrações",
    shortDescription: "Como o Atlas Connect conversa com ERP, TMS e rastreadores de diferentes fabricantes.",
    durationMinutes: 30,
    academy: "totaltrac", status: "ready", category: "Soluções Total Trac",
  },
  {
    slug: "08-clientes",
    number: 8,
    title: "Clientes",
    shortDescription: "Perfis de cliente atendidos pela Total Trac: transportadoras, embarcadores e segmentos.",
    durationMinutes: 30,
    academy: "totaltrac", status: "ready", category: "Mercado e clientes",
  },
  {
    slug: "09-processo-comercial",
    number: 9,
    title: "Processo Comercial",
    shortDescription: "ICP, persona, dores, objeções, diferenciais competitivos e argumentação.",
    durationMinutes: 40,
    academy: "totaltrac", status: "ready", category: "Mercado e clientes",
  },
  {
    slug: "10-termos-tecnicos",
    number: 10,
    title: "Termos Técnicos",
    shortDescription: "Glossário consolidado com os termos usados no dia a dia da Central e do mercado.",
    durationMinutes: 30,
    academy: "totaltrac", status: "ready", category: "Excelência operacional",
  },
  {
    slug: "11-operacao",
    number: 11,
    title: "Operação",
    shortDescription: "Fluxos, monitoramento, checklist, alertas e eventos do dia a dia da Central.",
    durationMinutes: 45,
    academy: "totaltrac", status: "ready", category: "Excelência operacional",
  },
  {
    slug: "12-compliance",
    number: 12,
    title: "Compliance",
    shortDescription: "LGPD, segurança da informação, sigilo e boas práticas internas.",
    durationMinutes: 30,
    academy: "totaltrac", status: "ready", category: "Excelência operacional",
  },
  {
    slug: "13-tecnologia",
    number: 13,
    title: "Tecnologia",
    shortDescription: "IA, analytics e automações aplicadas ao gerenciamento de risco logístico.",
    durationMinutes: 35,
    academy: "totaltrac", status: "ready", category: "Excelência operacional",
  },
  {
    slug: "14-casos-reais",
    number: 14,
    title: "Casos Reais",
    shortDescription: "Cases, recuperações e resultados operacionais da Total Trac.",
    durationMinutes: 30,
    academy: "totaltrac", status: "ready", category: "Excelência operacional",
  },
  {
    slug: "15-preparacao-final",
    number: 15,
    title: "Preparação Final",
    shortDescription: "Revisão geral de todo o conteúdo antes da prova final.",
    durationMinutes: 30,
    academy: "totaltrac", status: "ready", category: "Conclusão",
  },

  // --- TOTAL TRACK MODULES ---
  {
    slug: "tt-00-bem-vindo",
    number: 16,
    title: "Bem-vindo à Total Trac",
    shortDescription: "Apresentação da empresa, ecossistema e visão geral de tecnologias e soluções logísticas.",
    durationMinutes: 30,
    academy: "totaltrac", status: "ready", category: "Fundamentos Total Trac",
  },
  {
    slug: "tt-01-total-auto-4g",
    number: 17,
    title: "Total Auto 4G",
    shortDescription: "Monitoramento completo do veículo, controle de desempenho e segurança com opções de RFID e Bloqueio.",
    durationMinutes: 40,
    academy: "totaltrac", status: "ready", category: "Soluções para Veículos",
  },
  {
    slug: "tt-02-total-maquinas-4g",
    number: 18,
    title: "Total Máquinas 4G",
    shortDescription: "Gestão de máquinas pesadas e equipamentos com controle de horas e áreas de trabalho.",
    durationMinutes: 30,
    academy: "totaltrac", status: "ready", category: "Soluções para Máquinas e Ativos",
  },
  {
    slug: "tt-03-total-temperatura-4g",
    number: 19,
    title: "Total Temperatura 4G",
    shortDescription: "Controle de cargas sensíveis com monitoramento de variações térmicas em tempo real.",
    durationMinutes: 35,
    academy: "totaltrac", status: "ready", category: "Monitoramento Especializado",
  },
  {
    slug: "tt-04-total-jornada-4g",
    number: 20,
    title: "Total Jornada 4G",
    shortDescription: "Controle de jornada online, reduzindo riscos trabalhistas e automatizando processos burocráticos.",
    durationMinutes: 40,
    academy: "totaltrac", status: "ready", category: "Monitoramento Especializado",
  },
  {
    slug: "tt-05-carreta-solar",
    number: 21,
    title: "Carreta Solar",
    shortDescription: "Monitoramento inteligente de implementos com painel solar e bateria de longa duração.",
    durationMinutes: 30,
    academy: "totaltrac", status: "ready", category: "Soluções para Máquinas e Ativos",
  },
  {
    slug: "tt-06-kit-autonomia",
    number: 22,
    title: "Kit Autonomia (Carreta 4G)",
    shortDescription: "Rastreamento de carretas com foco em segurança, possuindo bateria para até 30 dias desengatada.",
    durationMinutes: 35,
    academy: "totaltrac", status: "ready", category: "Soluções para Máquinas e Ativos",
  },
  {
    slug: "tt-07-imobilizador",
    number: 23,
    title: "Imobilizador 4G",
    shortDescription: "Proteção contra roubo e uso indevido, resistente a Jammer, com atuação inteligente autônoma.",
    durationMinutes: 45,
    academy: "totaltrac", status: "ready", category: "Segurança",
  },
  {
    slug: "tt-08-total-safe",
    number: 24,
    title: "Total Safe (Videotelemetria)",
    shortDescription: "Câmeras com IA para monitoramento de comportamento, detecção de fadiga, distração e prevenção de acidentes.",
    durationMinutes: 45,
    academy: "totaltrac", status: "ready", category: "Segurança",
  }
];

export function getModuleMeta(slug: string): ModuleMeta | undefined {
  return moduleMetas.find((m) => m.slug === slug);
}
